version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3336:3336"
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3030 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3030:3030"
    depends_on:
      - db